version: '3.8'

services:
  scm-web:
    image: sportscarnivalmanagerv2:latest
    ports: 
      - '3000:3000'
    container_name: scm-web
    depends_on:
      - scm-db

  scm-db: 
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_ROOT_PASSWORD: $MYSQL_PW
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - scm-vol:/var/lib/mysql
    container_name: scm-db
    
volumes:
  scm-vol: