version: '3.8'

services:
  scm-web:
    build:
      context: .
    restart: always
    ports: 
      - '3000:3000'
    container_name: scm-web
    depends_on:
      - scm-db

  scm-db: 
    build:
      context: scm-db
      args:
        MYSQL_DB: $MYSQL_DB
        MYSQL_PW: $MYSQL_PW
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - scmdb-vol:/var/lib/mysql
    container_name: scm-db
    
volumes:
  scmdb-vol: